### PR TITLE
Replace num-bigint with malachite-bigint

### PR DESCRIPTION
**Pull request by qingshi163**

### CODE REVIEW

**Review by youknowone — APPROVED** [review]

**Comment by youknowone** [comment]
I wish we can see https://github.com/RustPython/RustPython/pull/4952 success before merging this PR

**Review by DimitrisJim — APPROVED** [review]
Nice. We should also remember to benchmark this change at some point since I'd assume the benefit of the small int optimization would show.

**Comment by qingshi163** [comment]
We need to check compatibility for RustPython and Ruff, also the benchmark mentioned by @DimitrisJim

**Comment by qingshi163** [comment]
I see the new merged pr #25 witch import pyo3 module with num-bigint feature. I did not work with pyo3 at all, don't know how heavy it will affect this pr.

@youknowone if possible can you help the rebase?

**Comment by youknowone** [comment]
sure, i will

**Comment by youknowone** [comment]
@qingshi163 is num-bigint to malachite-bigint conversion possible?

**Comment by qingshi163** [comment]
> @qingshi163 is num-bigint to malachite-bigint conversion possible?

sure it is convertable with very low cost. I will add the convertion function with feature flag in malachite-bigint

**Comment by qingshi163** [comment]
I have done the conversions on the malachite-bigint side. @youknowone

**Review by MichaReiser — COMMENTED** [review]
Nice! Can we try to run some benchmarks on this. For example, you can checkout ruff, change the parser dependencies to your local checkout, and run its parser benchmarks (i van write up some in detail explanation if needed but am on my phone right now)

**Comment by youknowone** [comment]
Great! Patching Ruff to use malachite_bigint was unbelievably easy.

**Comment by youknowone** [comment]
Everything seems fine and working great!

@qingshi163 I will finish this PR. A little bit of concern is `From<num_bigint::BigInt> for malachite_bigint::BigInt` is supported, but not `AsRef<malachite_bigint::BigInt> for num_bigint::BigInt`.
When using our AST, we usually can get `&BigInt` but not `BigInt` except for `Fold`, which is not very popular feature.
Because `num-bigint` is still a fundamental part of Rust environment (yet), supporting both bigint library for a while will make sense. `num-bigint` and `malachite-bigint` will be exclusive features and `malachite-bigint` will be the default.

I hope malachite-bigint replace more num-bigint use case.

**Pull request merged**
