### PR TITLE
0.3.0

### PR DESCRIPTION
**Pull request by youknowone**
#67

### CODE REVIEW

**Comment by youknowone** [comment]
I am getting confused how should I handle `ruff_text_size`. is it expected to published to crates.io?

@charliermarsh @MichaReiser

**Comment by charliermarsh** [comment]
@MichaReiser - Maybe we should just publish `ruff_text_size` to `crates.io` separately, and remove it as a local dependency here?

**Comment by youknowone** [comment]
@MichaReiser could you also check this?

**Comment by youknowone** [comment]
@charliermarsh @MichaReiser do you mind if I create a crate and transfer its ownership to you?

**Comment by MichaReiser** [comment]
> @charliermarsh @MichaReiser do you mind if I create a crate and transfer its ownership to you?

I would prefer using a different name, e.g. `rustpython-text-size`. We integrated the RustPyton into Ruff's mono repo and that includes `ruff_text_size`. There's a chance that our two crates will diverge over time, and that could lead to weird incompatibilities in the future.

**Comment by youknowone** [comment]
Thanks for replying

**Comment by youknowone** [comment]
0.3.0 is published

**Pull request merged**
